name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "luajit-2.0.5"
    - uses: leafo/gh-actions-luarocks@v2

    - name: build
      run: |
        luarocks install busted
    - name: test1
      run: |
        lua ${{ github.workspace }}/HeadlessWrapper.lua
      continue-on-error: true
    - name: test2
      run: |
        busted --no-auto-insulate --lpath=${{ github.workspace }} --cpath=${{ github.workspace }} ${{ github.workspace }}/HeadlessWrapper.lua
