name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "luajit-2.0.5"
    - uses: leafo/gh-actions-luarocks@v2
      
    - name: setup
      run: |
        unzip runtime-win32.zip

    - name: build
      run: |
        luarocks install busted
    - name: integration test
      run: |
        busted --verbose --no-auto-insulate --lpath=${{ github.workspace }}/lua/?.lua ${{ github.workspace }}/spec
